services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_api_php
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - db_test
    environment:
      DATABASE_URL: mysql://symfony:symfony@db:3306/symfony
      DATABASE_URL_TEST: mysql://symfony:symfony@db_test:3306/symfony_test

  db:
    image: mysql:8.0
    container_name: symfony_api_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  db_test:
    image: mysql:8.0
    container_name: symfony_api_db_test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db-test-data:/var/lib/mysql

volumes:
  db-data:
  db-test-data:
